web:
  build: .
  container_name: app_api
  command: bash -c "npm i && npm rebuild && npm start"
  volumes:
    - .:/api
    - /app/node_modules
  ports:
    - "3000:3000"
  links:
    - mongo
    - redis
mongo:
  image: mongo:latest
  container_name: mongo_api
redis:
  image: redis:latest 
